# Dongle mode
CONFIG_ZMK_SPLIT_BLE_CENTRAL_PERIPHERALS=2

# USB
CONFIG_USB_DEVICE_STACK=y
CONFIG_USB_DEVICE_HID=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_USB_BOOT=y
CONFIG_USB_HID_POLL_INTERVAL_MS=10

# No sleep on dongle (USB-powered)
CONFIG_ZMK_SLEEP=n

# ZMK Studio
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_STUDIO_LOCKING=n
CONFIG_ZMK_STUDIO_LOCK_ON_DISCONNECT=n
