# 更改键盘默认显示名称
CONFIG_ZMK_KEYBOARD_NAME="PandaKB_Corne"
#EC11 enable
#CONFIG_EC11=y
#CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y



CONFIG_BT_CTLR_TX_PWR_PLUS_8=y
CONFIG_ZMK_HID_REPORT_TYPE_NKRO=n

CONFIG_ZMK_DISPLAY=y
